# Generated by Django 5.0.1 on 2024-01-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_alter_desafio_user_alter_flashcard_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
