# Name of the workflow
name: Django CI

# Set the event trigger to push and pull request in every branch
on: [push, pull_request]

# Set the jobs to run
jobs:
  build:
    runs-on: ubuntu-latest
    
    # Run three parallel jobs for each python version
    strategy:
      max-parallel: 3
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    
    # Get the code from the repository
    steps:
    - uses: actions/checkout@v3
    
    # Set up the python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      run: python manage.py test
